"""
Missiles submodule — extract missile metadata (Type, Size, Manufacturer, Name)
from DataForge records and write missile_overrides.ini with formatted names.

Missile types are:
  EM — Electromagnetic
  IR — Infrared
  CS — CrossSection

Prerequisite: unforge.exe must have already been run to unpack Game2.dcb.
"""

import re
import xml.etree.ElementTree as ET

from sc_config import (
    DATA_ROOT,
    SRC_GLOBAL_INI,
    MISSILES_INI,
    step,
)

MISSILES_ROOT = DATA_ROOT / "entities" / "scitem" / "ships" / "weapons" / "missiles"

# Map from entity class name pattern to missile type abbreviation
MISSILE_TYPE_MAP = {
    "_CS_": "CS",  # CrossSection
    "_EM_": "EM",  # ElectroMagnetic
    "_IR_": "IR",  # InfraRed
}

_RE_ENTITY = re.compile(r"<EntityClassDefinition\.(\S+)\s")
_RE_TYPE_IN_ENTITY = re.compile(r"_(CS|EM|IR)_")

_KEY_MAP: dict[str, str] = {}


def _load_key_map(path) -> dict[str, str]:
    """Return lowercase_key → original_case_key for every key=value line in path."""
    global _KEY_MAP
    if _KEY_MAP:
        return _KEY_MAP

    key_map: dict[str, str] = {}
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            eq = line.find("=")
            if eq > 0:
                orig_key = line[:eq].strip()
                if orig_key:
                    key_map[orig_key.lower()] = orig_key
    _KEY_MAP = key_map
    return key_map


def _extract_missile_type(entity_class: str, content: str) -> str | None:
    """Extract missile type from entity class name or XML content.

    Checks entity class name first for pattern like GMISL_S01_CS_FSKI_Spark,
    then looks in XML trackingSignalType if not found.
    """
    match = _RE_TYPE_IN_ENTITY.search(entity_class)
    if match:
        return match.group(1)

    # Fallback: check trackingSignalType in XML
    try:
        signal_match = re.search(r'trackingSignalType="(\w+)"', content)
        if signal_match:
            signal_type = signal_match.group(1)
            # Map from XML signal type to abbreviation
            if signal_type == "CrossSection":
                return "CS"
            elif signal_type == "ElectroMagnetic":
                return "EM"
            elif signal_type == "InfraRed":
                return "IR"
    except Exception:
        pass

    return None


def _parse_missile_file(path) -> tuple[str, str] | None:
    """Parse missile XML and return (entity_class, missile_type).

    Returns None if file cannot be parsed or type cannot be determined.
    """
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()

        # Extract entity class
        match = _RE_ENTITY.search(content)
        if not match:
            return None

        entity_class = match.group(1)
        missile_type = _extract_missile_type(entity_class, content)

        if not missile_type:
            return None

        return entity_class, missile_type
    except Exception:
        return None


def _get_missile_name(key_map: dict[str, str], entity_class: str) -> str | None:
    """Look up the missile display name from localization.

    Searches for item_NameENTITY_CLASS variants in the key map.
    Returns the name part (after any prefix) or None if not found.
    """
    base = entity_class
    # Try exact match first
    lower = f"item_name{base}".lower()
    if lower in key_map:
        return None  # We'll return the original key, not the name

    return None


def build_missiles_ini(rows: list[dict], key_map: dict[str, str]) -> tuple[int, str]:
    """Build localization overrides INI for missiles with formatted names.

    Writes entries like:
      item_NameGMISL_S01_CS_FSKI_Spark=[CS] Spark I-G Missile

    Args:
        rows: List of dicts with keys: entity_class, missile_type, base_name
        key_map: Localization key map

    Returns:
        (count, ini_content) — number of entries written and the ini content.
    """
    lines: list[str] = []
    lines.append("; Missile name overrides — formatted as [TYPE] NAME")
    lines.append("; Auto-generated by sc_missiles.py")
    lines.append("")

    count = 0
    for row in sorted(rows, key=lambda r: r["entity_class"]):
        entity_class = row["entity_class"]
        missile_type = row["missile_type"]
        base_name = row["base_name"]

        # Look for localization key variants
        loc_key = None
        loc_value = None
        for variant in [
            f"item_Name{entity_class}",
            f"item_Name{entity_class}_SCItem",
        ]:
            lower = variant.lower()
            if lower in key_map:
                loc_key = key_map[lower]
                break

        if loc_key:
            # Format as [TYPE] Original_Name
            # The full name from localization is already in merged global.ini
            # We'll look it up to preserve the full original name
            formatted_name = f"[{missile_type}] {base_name}"
            lines.append(f"{loc_key}={formatted_name}")
            count += 1

    lines.append("")
    return count, "\n".join(lines)


def _get_full_missile_name_from_ini(
    key_map: dict[str, str], entity_class: str
) -> str | None:
    """Get the full missile name from the source global.ini.

    Args:
        key_map: Localization key map
        entity_class: Entity class name

    Returns:
        The original missile name or None.
    """
    for variant in [f"item_Name{entity_class}", f"item_Name{entity_class}_SCItem"]:
        lower = variant.lower()
        if lower in key_map:
            return key_map[lower]
    return None


def extract_missiles() -> int:
    """Parse all missile XML files (ship and ground vehicle variants) and return count.

    Returns the number of missiles found.
    """
    step("Extracting missile data")

    if not MISSILES_ROOT.exists():
        print(f"  No missiles directory found at {MISSILES_ROOT}")
        return 0

    # Find both ship (misl_) and ground vehicle (gmisl_) missiles
    missile_files = sorted(MISSILES_ROOT.glob("misl_*.xml")) + sorted(
        MISSILES_ROOT.glob("gmisl_*.xml")
    )
    if not missile_files:
        print(f"  No missile files found in {MISSILES_ROOT}")
        return 0

    key_map = _load_key_map(SRC_GLOBAL_INI)

    rows = []
    for path in missile_files:
        result = _parse_missile_file(path)
        if result:
            entity_class, missile_type = result

            # Look up the full name from global.ini localization
            full_name = None
            for variant in [
                f"item_Name{entity_class}",
                f"item_Name{entity_class}_SCItem",
            ]:
                lower = variant.lower()
                if lower in key_map:
                    # Read the value from the INI file
                    with open(SRC_GLOBAL_INI, encoding="utf-8", errors="replace") as f:
                        for line in f:
                            if line.startswith(key_map[lower] + "="):
                                full_name = line.split("=", 1)[1].rstrip("\n")
                                break
                    if full_name:
                        break

            if not full_name:
                # Fallback to just the last part of entity name
                parts = entity_class.split("_")
                full_name = parts[-1] if parts else "Unknown"

            rows.append(
                {
                    "entity_class": entity_class,
                    "missile_type": missile_type,
                    "base_name": full_name,
                }
            )

    print(f"  Found {len(rows)} missiles")

    if rows:
        count, ini_content = build_missiles_ini(rows, key_map)

        MISSILES_INI.parent.mkdir(parents=True, exist_ok=True)
        with open(MISSILES_INI, "w", encoding="utf-8") as f:
            f.write(ini_content)

        print(f"  Wrote {count} entries → {MISSILES_INI}")
        return count

    return 0
