items_commodities_hephaestanite_raw=Heph (Raw)
; Manual overrides — these take priority over ship_components.ini
item_NameSHLD_GODI_S04_Idris=Holdstrong (Mi/A)
vehicle_NameANVL_Hornet_F7A_Mk2_PYAM_Exec=Anvil F7A Hornet Mk II PYAM Exec
vehicle_NameANVL_Lightning_F8C_PYAM_Exec=Anvil F8C Lightning PYAM Exec
vehicle_NameCRUS_Starfighter_Ion_Collector_Stealth=Crusader Ares Star Fighter Ion Wikelo Sneak Special
vehicle_NameDRAK_Corsair_PYAM_Exec=Drake Corsair PYAM Exec
vehicle_NameDRAK_Cutlass_Black_PYAM_Exec=Drake Cutlass Black PYAM Exec
vehicle_NameGAMA_Syulen_PYAM_Exec=Gatac Syulen PYAM Exec
vehicle_NameRSI_Perseus=! RSI Perseus
vehicle_NameRSI_Zeus_ES=! RSI Zeus Mk II ES
salvage_FillerStation_TotalInternalStorage=Total Storage:
